# This file's content is a copy of the file located at src/resources/config/generator_options.yml.
# Which options file is used:
# - the one indicated by the --config option OR
# - your wsdltophp.yml file located where the command line is executed OR
# - this file if it exists OR
# - the original file located at src/resources/config/generator_options.yml.

category:
    default: 'cat'
    values: [ 'none', 'cat' ]
gather_methods:
    default: 'none'
    values: ['start', 'end', 'none' ]
generic_constants_names:
    default: false
    values: [ true, false ]
generate_tutorial_file:
    default: true
    values: [ true, false ]
add_comments:
    default: [ ]
    values: null
namespace_prefix:
    default: 'ericchew87\WWEXSpeedShip2PHP'
    values: ''
standalone:
    default: false
    values: [ true, false ]
validation:
    default: true
    values: [ true, false ]
struct_class:
    default: '\WsdlToPhp\PackageBase\AbstractStructBase'
    values: ''
struct_array_class:
    default: '\WsdlToPhp\PackageBase\AbstractStructArrayBase'
    values: ''
soap_client_class:
    default: '\WsdlToPhp\PackageBase\AbstractSoapClientBase'
    values: ''
origin:
    default: ''
    values: ''
destination:
    default: ''
    values: ''
prefix:
    default: ''
    values: ''
suffix:
    default: ''
    values: ''
basic_login:
    default: ''
    values: ''
basic_password:
    default: ''
    values: ''
proxy_host:
    default: ''
    values: ''
proxy_port:
    default: ''
    values: ''
proxy_login:
    default: ''
    values: ''
proxy_password:
    default: ''
    values: ''
soap_options:
    default: []
    values: null
composer_name:
    default: 'ericchew87\wwex-speedship2-php'
    values: ''
composer_settings:
    default: []
    values: ''
structs_folder:
    default: 'Structs'
    values: ''
arrays_folder:
    default: 'Arrays'
    values: ''
enums_folder:
    default: 'Enums'
    values: ''
services_folder:
    default: 'Services'
    values: ''
